-- SELECT UTILIZADO PARA CRIAÇÃO DO PARÂMETRO DE BUSCA
 SELECT CD, DS FROM 
 (SELECT '111,121,211,1,2,3,4,5,6' AS CD, 'PAI' AS DS, 1 AS ORDEM FROM DUAL
 UNION ALL
 SELECT '152' AS CD, 'UNIDADE 3' AS DS, 3 AS ORDEM FROM DUAL
 UNION ALL
 SELECT '181,182,281' AS CD, 'UNIDADE 3' AS DS, 2 AS ORDEM FROM DUAL
 UNION ALL
 SELECT '262' AS CD, 'HOME CARE' AS DS, 4 AS ORDEM FROM DUAL)
 ORDER BY ORDEM 


--SELECT PRINCIPAL PARA TRAZER AS ESCALAS 
SELECT UPPER(ES.DS_ESCALA) ESCALA,
       UPPER(SUBSTR(TASY.OBTER_DIA_SEMANA(TO_DATE(ED.DT_INICIO,
                                                  'DD/MM/RRRR hh24:mi:ss')),
                    1,
                    3)) DIASEMANA,
       TO_CHAR(ED.DT_INICIO, 'dd/mm') DIA,
       TO_CHAR(ED.DT_INICIO, 'hh24:ss') || ' - ' ||
       TO_CHAR(ED.DT_FIM, 'hh24:ss') HORARIO,
       CASE INSTR(PF.NM_PESSOA_FISICA, ' ')
    WHEN 0 THEN 
      PF.NM_PESSOA_FISICA 
    ELSE
      CASE INSTR(PF.NM_PESSOA_FISICA, ' ', INSTR(PF.NM_PESSOA_FISICA, ' ')+1, 1)
        WHEN 0 THEN
          PF.NM_PESSOA_FISICA
        ELSE
          SUBSTR(PF.NM_PESSOA_FISICA, 1, INSTR(PF.NM_PESSOA_FISICA, ' ', INSTR(PF.NM_PESSOA_FISICA, ' ')+1, 1))
      END
  END AS MEDICO
  FROM ESCALA_DIA ED, ESCALA ES, PESSOA_FISICA PF
 WHERE ED.NR_SEQ_ESCALA = ES.NR_SEQUENCIA
   AND PF.CD_PESSOA_FISICA = ED.CD_PESSOA_FISICA
   AND TRUNC(ED.DT_INICIO) >= $P{DATA_INICIAL} -- PARAMETRO DO JASPERSOFT REPORT
   AND TRUNC(ED.DT_FIM) <= $P{DATA_FINAL} -- PARAMETRO DO JASPERSOFT REPORT
   AND 
      (
        $P{ESCALA} IS NULL -- PARAMETRO DO JASPERSOFT REPORT
        OR
        EXISTS(SELECT 1
                FROM TASY.ESCALA_DIARIA ED2
                WHERE ED.NR_SEQUENCIA = ED2.NR_SEQUENCIA
                  AND ED2.NR_SEQ_ESCALA IN (
                            select regexp_substr( $P{ESCALA} ,'[^,]+', 1, level) from dual -- TRAZ A ESCALA SELECIONADA NO COMBO
                               connect by regexp_substr($P{ESCALA} , '[^,]+', 1, level) is not NULL
                          ) -- PARAMETRO DO JASPERSOFT REPORT, AQUI UTILIZANDO OS PARAMETROS MONTADOS NO INICIO DO ARQUIVO E PROCESSANDO PARA QUE SEJA POSSÍVEL TRATAR AS UNIDADES
               )
      )
